### ISSUE TITLE
Please remove [IN PROGRESS] from "CSS as first-class citizen"

### ISSUE THREAD

**Issue by glen-84** [webpack-contrib/voting-app#14]
It doesn't seem to be in progress anymore, and I'd like to be able to vote on it.

It would also be nice to have "HTML as first-class citizen" and "Files/assets/URLs as first-class citizen".

**Comment by evilebottnawi** [comment]
@glen-84 it is in progress for `webpack@5`, just no prioerity

**Comment by glen-84** [comment]
It may be *planned* for webpack 5 (although it's not even on the [project page](https://github.com/webpack/webpack/projects/5)?), but as far as I can tell, it's certainly not *in progress*.

**Comment by evilebottnawi** [comment]
@glen-84 feel free to send a PR

**Comment by glen-84** [comment]
Where is the data stored?

**Comment by glen-84** [comment]
@skipjack Where is the data stored?

**Comment by skipjack** [comment]
I believe it’s stored somewhere in AWS, managed by @sokra or @thelarkinn. You can see the REST calls we make for the data here:

https://github.com/webpack-contrib/voting-app/blob/master/src/utils/js/api.js

**Comment by glen-84** [comment]
I guess I can't send a PR then. 🙂

**Comment by skipjack** [comment]
True but you could reach out to them and ask nicely 😜... @TheLarkInn @sokra I think there's two questions here:

1. [short term] Can one of you make the update to the above-mentioned vote item?
2. [long term] Maybe there's a better way to expose this data? Since the amount of data is minimal it could be exposed in this repo instead which would allow people to PR changes with your review.

As for the second point, idk the rationale behind it being stored in AWS in the first place so I could definitely be missing a valid concern.

**Comment by sokra** [comment]
I updated it.

It need to have a backend to allow voting. Technically it's possible to put the info into github, but it also works great this way.

**Comment by glen-84** [comment]
I can vote now (thanks), but the title still includes `[IN PROGRESS]`.

Also, is there any chance that we could get "HTML as first-class citizen" and "Files/URLs as first-class citizen"?

**Comment by sokra** [comment]
sure, added.

**Comment by glen-84** [comment]
> sure, added.

Awesome! Thanks a lot.

> yep, because we already have worked towards this.

The infrastructure for module types in general, or something specific to CSS? (or the work related to the mini-css-extract-plugin?)

"In progress" generally means "currently happening", but anyway I'm just happy that I'm able to vote for it now. 🙂 

Thanks for the work that you do.

**Comment by sokra** [comment]
> The infrastructure for module types in general, or something specific to CSS? (or the work related to the mini-css-extract-plugin?)

with webpack 4 and the mini-css-extract-plugin, CSS is already a module type, which has a lot of benefits (like code-splitting).

webpack 5 will add the ability to support HMR for other module types and MCEP will be improved towards this.

**Comment by glen-84** [comment]
I'm looking forward to the day that MCEP is not even required. HTML and CSS entry points will make working with non-JS modules so much easier and more logical.

https://github.com/webpack/webpack/issues/536 has the most 👍, so I'm not the only one waiting for this feature. 🙂
