### ISSUE TITLE
Your browser is not supported.

### ISSUE THREAD

**Issue by glen-84** [webpack-contrib/voting-app#15]
I get this message when I click "Login with GitHub".

I'm using Firefox 65.0.1 (64-bit).

**Comment by skipjack** [comment]
I'm seeing the same thing on Chrome Version 72.0.3626.109 (Official Build) (64-bit) on MacOS.

**Comment by skipjack** [comment]
This may have been caused by the recent webpack.js.org release somehow.

cc @montogeek

**Comment by skipjack** [comment]
Although, it's really just coming from these lines (top and bottom) which seem straightforward enough:

https://github.com/webpack-contrib/voting-app/blob/master/src/components/wrapper/wrapper.jsx#L20-L41

@montogeek maybe the build process changes caused this somehow? I don't remember seeing this issue during initial development on the `rebuild` branch but maybe this is a dev vs prod parity issue.

**Comment by skipjack** [comment]
Funny if I load another page, then navigate to `/vote`, it works fine. Only on refresh do I see the message. That's a pretty good indicator that something's up with the build in the main `webpack.js.org` repo I think.

**Comment by montogeek** [comment]
@EugeneHlushko Changed how the voting app was imported. Could you please check it if you have time? I can do it tonight, in ~10 hours

**Comment by cowwoc** [comment]
@montogeek It's still broken for me. Chrome 72.0.3626.119.

**Comment by chriscalo** [comment]
> Funny if I load another page, then navigate to `/vote`, it works fine.

For people just trying to get to the `/vote` page, if this is indeed true, can someone post a link to any page that links to the `/vote` page? I'm not able to find a link to it anywhere.

**Comment by skipjack** [comment]
The link is missing from the mobile sidebar but on desktops or laptops you can find it in the top right of the banner.

**Comment by Janpot** [comment]
Even if you manage to get there by following the link, the login doesn't work.

**Comment by montogeek** [comment]
@glen-84 Can you please try again?

**Comment by skipjack** [comment]
Works for me now, thanks @montogeek!

**Comment by glen-84** [comment]
@montogeek It's working now, thanks! 🎉
