### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by skipjack** [webpack-contrib/voting-app#3]
Moving this conversation from webpack/webpack.js.org#409...

@pksjce the CTA for vote buttons, especially on mobile, are definitely still an issue. If someone has a good idea to rectify this, I'd be happy to incorporate it into the design.

> Note: At some point I'll likely be migrating these comps to sketch, but if there are any quick fixes I can make them in the current version. I'll push the current updates to the webpack-design repo as well at some point today.

Here are all the comps for reference:

__Logged Out__

![image](https://cloud.githubusercontent.com/assets/8988697/25065666/6e068d80-21e1-11e7-9cb8-3af3fdd2620a.png)

__Logged in as a Normal User__

![image](https://cloud.githubusercontent.com/assets/8988697/25065672/7be337c8-21e1-11e7-8b18-6dc604c6b51d.png)

__Logged in as an Admin__

![image](https://cloud.githubusercontent.com/assets/8988697/25065673/896a72da-21e1-11e7-8623-46d3aa042132.png)

__Admin Settings Menu__

![image](https://cloud.githubusercontent.com/assets/8988697/25065680/93c4d496-21e1-11e7-8106-c578efe06d99.png)

__Mobile__

![image](https://cloud.githubusercontent.com/assets/8988697/25065687/a7c26418-21e1-11e7-860c-54c27a3142bb.png)

**Comment by michael-ciniawsky** [comment]
The plus sign in the 'calc section' looks misplaced somehow and an underline between the summands and the total would be nice :)

```
Golden Influence (+ / - )
Influence ( +/ - )
--------------------
Total 
```

**Comment by skipjack** [comment]
@michael-ciniawsky are you just talking about the mobile comp?

> The plus sign in the 'calc section' looks misplaced somehow...

Yea in the mobile comp I see what you mean.. maybe bring it in closer to the count?

> ... and an underline between the summands and the total would be nice :)

In the normal comp there already is one but when I tried to incorporate it into the mobile version it felt a little odd. Any chance you'd be interested in making tweaks and submitting them as a PR over at the [design repo](/skipjack/webpack-design)? (or just sharing them here) I just pushed all my latest changes up.

**Comment by michael-ciniawsky** [comment]
@skipjack Yep mobile 😛 but the plus in general

> Any chance you'd be interested in making tweaks and submitting them as a PR over at the design repo?

Sry I don't use Photoshop/Sketch myself, when I design I'm programming it since I'm *no* real designer :D

**Comment by skipjack** [comment]
Haha, no worries... I may make the updates myself to the comps but either way whoever starts PR-ing the actual redesign can take the the things mentioned here into account. I'll be submitting a refactoring PR here within the next 24 but after that I'll likely be shifting back to webpack.js.org issues/tasks.

**Comment by skipjack** [comment]
Ok I may try to tackle this redesign soon if I can find the time. Would be great if we could find someone to maintain this repo longterm though.
