### ISSUE TITLE
Github Login Broken

### ISSUE THREAD

**Issue by TheLarkInn** [webpack-contrib/voting-app#9]
After #3 I was testing things out quickly to see if it worked. 

It looks incredible but noticed there was a error trying to login on github. 

Here is an example of the error in question: 
<img width="1900" alt="screen shot 2017-12-26 at 5 28 31 pm" src="https://user-images.githubusercontent.com/3408176/34366515-47403602-ea62-11e7-88f7-7c2aa164a2e5.png">

I can try and tackle this myself also (cc @skipjack unless you know what this is off the bat)

**Comment by skipjack** [comment]
Yep noticed this as well, will review your PR now.
